# MySQL. Versions 5.1.10 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: user_story_development

test:
  <<: *default
  database: user_story_test
  
production:
  <<: *default
  database: user_story_production
  username: user_story
  password: <%= ENV['USER_STORY_DATABASE_PASSWORD'] %>
